Repository magicbell-io/react-headless, pull requests merged in 2022-02, with the labels that each got.

#14 fix: support category filters in notification store
  src/stores/notifications/helpers/strategies.ts
Labels: bug

#16 Feature: Addition of User Defined Label and New Channels
  src/types/IRemoteNotificationPreferences.ts
Labels: enhancement, Ready for review

#17 chore: replace faker with @faker-js/faker
  package.json
  tests/factories/ConfigFactory.ts
  tests/factories/NotificationFactory.ts
  tests/factories/NotificationPreferencesFactory.ts
  tests/src/components/MagicBellProvider/MagicBellProvider.spec.tsx
  tests/src/hooks/useMagicBellEvent.spec.ts
  tests/src/lib/ajax.spec.ts
  tests/src/lib/realtime.spec.ts
  tests/src/stores/notifications/NotificationRepository.spec.ts
  tests/src/stores/notifications/useNotificationStoresCollection.spec.ts
  yarn.lock
Labels: dependencies

#18 chore: Resolve or ignore linter issues
  .eslintrc.js
  src/hooks/useAbly.ts
  src/hooks/useMagicBellEvent.ts
  src/hooks/useNotificationUnmount.ts
  src/hooks/useNotifications.ts
  src/index.ts
  src/lib/json.ts
  src/lib/realtime.ts
  src/stores/notifications/helpers/strategies.ts
  src/stores/notifications/useNotificationStoresCollection.ts
  src/stores/repository/RemoteRepository.ts
  src/types/IRemoteNotification.ts
  tests/src/lib/realtime.spec.ts
  tests/src/stores/config/useConfig.spec.ts
  tests/src/stores/notification_preferences/useNotificationPreferences.spec.ts
  tests/src/stores/notifications/useNotificationStoresCollection.spec.ts
Labels: Ready for review
